# Generated by Django 3.1.12 on 2025-01-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0002_personel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.IntegerField()),
                ('gross', models.IntegerField()),
                ('insurance', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('personel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel.personel')),
            ],
        ),
    ]
