# Generated by Django 3.1.12 on 2025-01-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personel_user'),
        ('salary', '0002_auto_20250127_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='personnel.personel'),
        ),
    ]
